accounts/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from .import views
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup_view, name="signup"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from store.sitemaps import ProductSiteMap


sitemaps = {
    'product':ProductSiteMap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
    path(r'^tinymce/', include('tinymce.urls')),

    path('accounts/',include('accounts.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.STATICFILES_DIRS}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_URL}), 
 


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from .import views
from .views import *

urlpatterns = [

    path('',views.home, name="home"),

    path('store/',views.store, name="store"),


     path('about/', views.about_us, name="about"),


<<<<<<< HEAD
=======

>>>>>>> 27f118911aca704bb87409323351786b3ca256ff
     path("shipping_details/<int:pk>/", views.shipping_details,
         name="shipping_details"),
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),

    path('admin-customer/', views.view_customer.as_view(), name="customer"),

    path("admin-home/", AdminHomeView.as_view(), name="admin_home"),

    path("admin-logout/", admin_logout_view, name="admin_logout"),

    path("admin-products/", admin_products.as_view(), name="admin_products"),

    path("admin-orders/", admin_orders.as_view(), name="admin_orders"),

    path("admin-delivering/", views.out_for_delivery, name="delivering"),

    path("admin-delivered/", views.delivered, name="delivered"),

    path("admin-pending/", views.pending_orders, name="pending"),

    path('new_orders/<str:pk>/', views.new_order, name="new_orders"),


    path('update_item/', views.updateItem, name="update_item"),
    path('update_guest_item/', views.updateGuest_item, name="update_item"),

    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),

    path('blog/', views.article_list, name="list"),
    path('products/category/<str:pk>/', views.all_categories, name="category"),

     path('blog/article_details/<slug:slug>/', views.article_detail, name="article_details"),

    path("posts/<str:username>", UserPostListView.as_view(), name="user-posts"),




   # re_path(r'^(?P<slug>[\w-]+)/$', views.product_detail, name='detail'),
    path('product_details/<slug:slug>/', views.product_detail, name="detail"),

   # re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='article_details'),






    path('process_order/', views.process_order, name="process_order"),



#     path('create/', views.AdminProductCreateView.as_view(), name="create"),

    path('create/', views.AdminProductCreateView.as_view(), name="create"),


    path('carousel_edit/', views.carousel_detail, name="carousel"),

    path('update_product/<str:pk>/', views.update_product, name="update_product"),


    path('update_order/<str:key>/', views.update_order, name="update_order"),

    path('customer_details/', views.customer_view_details, name="customer_details"),

    path('export/', views.Export, name="export"),

    #path('update_order/<str:key>/', views.update_order, name="update_order"),

    path('delete_order/<str:pk>/', views.delete_order, name="delete_order"),

    path('delete_product/<str:pk>/', views.delete_product, name="delete_product"),


    







    path('search/', views.Search, name="search"),

    path('chart/', views.ClubChartView.as_view(), name="chart"),



    path("cust_details/<int:pk>/", views.detail_cust,
         name="cust_details"),

    #re_path(r'^(?P<slug>[\w-]+)/$', views.detail_cust, name='cust_details'),


    #re_path(r'^(?P<slug>[\w-]+)/$', views.admin_ordering, name='ordering'),

    

    #re_path(r'^(?P<slug>[\w-]+)/$', views.updateOrder, name='update_order'),

    path("admin-order/<int:pk>/", admin_ordering.as_view(),
         name="admindetail"),

     path("newsletter-signup/",views.newsletter_signup, name="newsletter"),

     path('aboutus/',views.about_us, name="about")

        #Excel Stuff
    


]

store/forms.py
from django import forms
from store.models import CarouselData, Product, Order, Category, OrderItem, Newsletter, Comments, Order_customer, ProductImage


class CarouselForm(forms.ModelForm):
    class Meta:
        model = CarouselData

        fields = ['body', 'image']

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-group row'}),

            "image": forms.ClearableFileInput(attrs={"class": "form-control"}),


        }


class CreateProduct(forms.ModelForm):
    """more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
        "class": "form-control",
        "multiple": True
    }))
    """
    class Meta:
        model = Product

        fields = ['name', 'price','category', 'digital', 'image' , 'description', 'slug',"featured",'created_by']

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-group row'}),
            'price': forms.TextInput(attrs={'class': 'form-group row'}),
           # 'category': forms.TextInput(attrs={'class': 'form-group row'}),
            'digital': forms.CheckboxInput(attrs={'class': 'form-group row'}),
            "image": forms.ClearableFileInput(attrs={"class": "form-control","multiple": True}),
            'description': forms.Textarea(attrs={'class': 'form-group row'}),
            'slug': forms.TextInput(attrs={'class': 'form-group row'}),
            'featured':forms.CheckboxInput(attrs={"class":'form-group row'})

        }

class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        exclude = ['quantity','Product','complete']

class UpdateProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class GeeksForm(forms.Form): 
    name = forms.CharField() 
    geeks_field = forms.ImageField() 

class CreateComment(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name','email','comment']

class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

        exclude = ['date']
class OrderCustomer(forms.ModelForm):
    class Meta:
        model = Order_customer
        fields = '__all__'

class ProductImageForm(forms.ModelForm):
    class Meta:
        model  = ProductImage
        fields = '__all__'

        exclude = ['product']

store/views.py
from django.views.generic import View, TemplateView, CreateView, FormView, DetailView, ListView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers
from json import dumps
from django.forms import modelformset_factory
from django.contrib import messages

from django_tables2.export.export import TableExport



from django.db.models import Q
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from bs4 import BeautifulSoup
import json
import datetime
import csv
import smtplib
import requests
import lxml

from .models import *
from .utils import cookieCart, cartData, guestOrder
from . import forms
from .forms import *
from .filters import OrderFilter, OrderHomeFilter

from .forms import CustomerLoginForm


# Create your views here.



def home(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    category = Category.objects.all()
    properties = SiteProperties.objects.get(purpose="Home Carousel")
    featured = Product.objects.filter(featured=True)
    articles = Article.objects.all().order_by('date')[0:5]
    json_serializer = serializers.get_serializer("json")()
    timer = json_serializer.serialize(Timer.objects.all(), ensure_ascii=False)

    response = requests.get('https://fakestoreapi.com/products')
    fake_product = response.json()
    print('Fake product', fake_product)
   

    if request.method == "POST": 
        form = NewsletterForm(request.POST)
       
        if form.is_valid():
            instance = form.save(commit = False)
            instance.save()
            return redirect('list')
         
            
    else: 
        form = NewsletterForm()



    products = Product.objects.all()[:5]

    context = {
        'items': items, 'order': order, 'cartItems': cartItems, 
        'products':products, 'articles':articles, 'timer':timer,
        'category':category,'properties':properties,'form':form,
        'featured':featured,'fake_product':fake_product,
    }

    return render(request, "store/boot_home.html", context)

def carousel_detail(request):
    context = {} 
    if request.method == "POST": 
        form = GeeksForm(request.POST, request.FILES) 
        if form.is_valid(): 
            name = form.cleaned_data.get("name") 
            img = form.cleaned_data.get("geeks_field") 
            obj = CarouselData.objects.create( 
                                 body = name,  
                                 image = img 
                                 ) 
            obj.save() 
            print(obj) 
    else: 
        form = GeeksForm() 
    context['form']= form 
    return render(request, "store/carousel_edit.html", context) 

def store(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    category = Category.objects.all()

    


    products = Product.objects.all()
    # context = {'Products': products}

    #carousel_content = CarouselData.objects.all()

    print(products, cartItems)
    return render(request, 'store/shop.html',
                  {'products': products, 'cartItems': cartItems, 'order':order,'items':items,'category':category})


def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    category = Category.objects.all()


    context = {'items': items, 'order': order, 'cartItems': cartItems,'category':category}
    return render(request, 'store/shopping-cart.html', context)


def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    category = Category.objects.all()
    if request.method == "POST": 
            form_order = OrderCustomer(request.POST)
        
            if form_order.is_valid():
                instance = form_order.save(commit = False)
                instance.save()
                return redirect('list')
            
                
    else: 
        form_order = OrderCustomer()


    context = {'items': items, 'order': order, 'cartItems': cartItems,'category':category,'form_order':form_order,} 
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)

    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def updateGuest_item(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)

    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

# def email_send():

#     email_details = Send_email.objects.all()
#     sender_email = "sosahlawe@gmail.com"
#     reciever_email = "mantsenii0@gmail.com"
#     message = "Transaction completed! By Lawe Sosah"

#     server = smtplib.SMTP('smtp.gmail.com',587)
#     server.starttls()
#     server.login(sender_email,password)
#     print("Login success")
#     server.sendmail(sender_email,reciever_email,message)
#     print("Email has been sent to", reciever_email)

def inventory():
    order = Order.objects.get(order=Order)
    orderitem = OrderItem.objects.get(order=order)
    for item in orderitem():
        product = item.product
        product.num_available = product.num_available - item.quantity
        product.save()

def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    print(total)

    if total == float(order.get_cart_total):
        order.complete = True
        # email_send() Remember to include this later
        # inventory()
        # for item in order.get_cart_quantity():
        #     product = item.product
        #     product.num_available = product.num_available - item.quantity
        #     product.save()
            
    order.save()

    

    

    print('total:', total)
    print('order.get_cart_total:', order.get_cart_total)
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            city=data['shipping']['city'],
            county=data['shipping']['county'],
        )


    return JsonResponse('Payment Complete!', safe=False)


def Search(request):
    data = cartData(request)
    cartItems = data['cartItems']

    kw = request.GET.get("keyword")
    results = Product.objects.filter(
        Q(name__icontains=kw) | Q(price__icontains=kw))
    print(results)

    return render(request, 'store/search.html', {'cartItems': cartItems, 'results': results})


def product_detail(request, slug):
    # return HttpResponse(slug)
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    products = get_object_or_404(Product, slug=slug)

    products.page_views = products.page_views+1
    new_views = products.page_views
    photos = ProductImage.objects.filter(product=products)
    print('Les views',new_views-1)
    products.save()

    reviews = ProductReview.objects.all()
    product = Product.objects.all()[:4]
    stars = ProductReview.objects.count() 

    if request.method == "POST": 
        form = NewsletterForm(request.POST)
       
        if form.is_valid():
            instance = form.save(commit = False)
            instance.save()
            return redirect('list')
         
            
    else: 
        form = NewsletterForm()

    if request.method == 'POST' and request.user.is_authenticated:
        stars = request.POST.get('stars', 3)
        content = request.POST.get('content','')

        review = ProductReview.objects.create(product=products, user=request.user, stars=stars, content=content  )

        return redirect('detail', slug=slug)


    #products = Product.objects.get(slug=slug)
    return render(request, 'store/product.html', {'products': products, 'cartItems': cartItems,'order':order,
                                                    'items':items,'product':product,'products':products,
                                                    'reviews':reviews, 'stars':stars,'form':form,'views':products.page_views,
                                                    'photos':photos})


# def product_create(request):

store/templates/store/aboutus.html
{% extends 'store/blog_base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
{% block nav %}{% include 'store/header.html' %}{% endblock nav%}
<style>
.parallax {
  /* The image used */
  background-image: url('/static/images/background1.jpg');

  /* Set a specific height */
  height: 500px;

  /* Create the parallax scrolling effect */
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>
<div class="parallax" style="padding:50px;
	text-align: center;
	background-image:url('/static/images/black_background.jpeg/');
	color: white">
    <h1 class="text-white">About Us Page</h1>
    <p class="text-white">We are dealers in Phones, Laptops and Accesories.</p>
    <p class="text-white">We are currently located at the Midway mall, Opposite Imenti House on the first floor, Shop U1.</p>
    </div>

        <div class="row parallax">
            <div class="col-6 col-md-4 ">
                <div class="product-item">
                
                    <div class="pi-pic">
                    <a href="#">
                        <img src="{% static 'images/avatar.jpeg'%}" alt="">
                    </a>                                        

                    </div>
                    <div class="pi-text">
                        <div class="catagory-name">Team Member</div>
                            <h5>Name</h5>
                            <br>
                            <p>Short description</p>
                                

                        <a href="#">
                            <h5>Name again?</h5>
                        </a>
                        
                    </div>

                </div>
            </div>

            <div class="col-6 col-md-4 ">
                <div class="product-item">
                
                    <div class="pi-pic">
                    <a href="#">
                        <img src="{% static 'images/avatar.jpeg'%}" alt="">
                    </a>                                        

                    </div>
                    <div class="pi-text">
                        <div class="catagory-name">Team Member</div>
                            <h5>Name</h5>
                            <br>
                            <p>Short description</p>
                                

                        <a href="#">
                            <h5>Name again?</h5>
                        </a>
                        
                    </div>

                </div>
            </div>

            <div class="col-6 col-md-4 ">
                <div class="product-item">
                
                    <div class="pi-pic">
                    <a href="#">
                        <img src="{% static 'images/avatar.jpeg'%}" alt="">
                    </a>                                        

                    </div>
                    <div class="pi-text">
                        <div class="catagory-name">Team Member</div>
                            <h5>Name</h5>
                            <br>
                            <p>Short description</p>
                                

                        <a href="#">
                            <h5>Name again?</h5>
                        </a>
                        
                    </div>

                </div>
            </div>

                    <hr>
                        <h5 class="aboot__h5" style="font-size: 30px;
        justify-content: center;
        margin-right:20px;
        padding:20px;"><strong> Feel free to send us a message below</strong></h5>
                    <hr>
                <div class="col-md-7" style="margin-right:20px;">
                    <div class="card card-body"  style="margin-right:30px; background-image=url('/static/images/black_background.jpeg/'); justify-content:center;">

                        <form action="{% url 'newsletter' %}" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {{field.label}}
                                {{field|add_class:'form-control'}}
                            
                            {% endfor %}
                            <hr>
                            <input type="submit" class="btn btn-info">
                        </form>
                </div>
        </div>
                </div>

    </div>

{% endblock content%}
{% block footer %}{% include 'store/footer_block.html' %}{% endblock footer %}

store/templates/store/carousel_edit.html
{% extends 'store/main.html' %}

{% block content %}

<hr>

<hr>
<form method="POST" enctype="multipart/form-data"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <input type="submit" value="Submit"> 
</form> 
{% endblock %}

store/templates/store/excel_home.html
{% extends 'store/base.html'%}

{% block content %}
   <h3>Excel Example - Read Write Examples</h3>
        <ul>
            <li>Write Operation
                <ul>
                    <li>
                        <a href="{% url 'export_excel' %}">Simple Excel Write Operation</a>
                    </li>
                    <li>
                        <a href="{% url 'export_styling_excel' %}">Styling your Excel data with xlwt</a>
                    </li>
                    <li>
                        <a href="#">writing to existng workbook using dnxlwt </a>
                    </li>
                </ul>
            </li>
        </ul>
{% endblock %}

store/templates/store/header.html
{% load static %}
{% load humanize %}
{% block header %}
<!-- Header Section Begin -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="ht-left">
                    <div class="mail-service">
                        <i class=" fa fa-envelope"></i>
                        lynamcomputers@gmail.com
                    </div>
                    <div class="phone-service">
                        <i class=" fa fa-phone"></i>
                            +254708835133
                    </div>
                </div>
                <div class="ht-right">
                {% if user.is_authenticated %}

                    <a href="{% url 'accounts:logout' %}" class="login-panel "><i class="fa fa-user"></i>Signout</a>
                    {% else %}
                        <a href="{% url 'accounts:login' %}" class="login-panel "><i class="fa fa-user"></i>Login</a>

                {% endif %}
                    <div class="lan-selector">
                        <select class="language_drop" name="countries" id="countries" style="width:300px;">
                            <option value='yt' data-image="{% static 'images/flag-1.jpg'%}" data-imagecss="flag yt"
                                data-title="English">English</option>
                            <option value='yu' data-image="img/flag-2.jpg" data-imagecss="flag yu"
                                data-title="Bangladesh">German </option>
                        </select>
                    </div>
                    <div class="top-social">
                        <a href="#"><i class="ti-facebook"></i></a>
                        <a href="#"><i class="ti-twitter-alt"></i></a>
                        <a href="#"><i class="ti-linkedin"></i></a>
                        <a href="#"><i class="ti-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="container">
        
            <div class="inner-header">
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-2 ">
                        <div class="logo">
                            <a href="{% url 'store' %}">
                            <img src="{% static 'images/lynam_black.jpg'%}" style="height:100px; width:auto; border-radius:50%;">
                            </a>
                        </div>
                    </div>


       
            

                    <div class="col-lg-7 col-md-7">
                        <div class="advanced-search">
                            <button type="button" class="category-btn" style="border-color:white; ">All Categories</button>
                            <form class="#" action="{% url 'search'%}" method="GET">

                            <div class="input-group">
                                <input name="keyword" class="form-control mr-sm-2 col-sm-4" type="search" placeholder="Search" aria-label="Search" required>
                                <button class="button" type="submit">
                                <i class="ti-search"></i>
                                </button>
                            </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-3 text-right col-md-3">
                        <ul class="nav-right">
                            <li class="heart-icon">
                                <a href="#">
                                    <i class="icon_heart_alt"></i>
                                    <span>1</span>
                                </a>
                            </li>
                            <li class="cart-icon">
                                <a href="#">
                                    <i class="icon_bag_alt"></i>
                                    <span>{{order.get_cart_items}}</span>
                                </a>
                                <div class="cart-hover">
                                    <div class="select-items">
                                        <table>
                                            <tbody>

                                            {% for item in items %}
                                                <tr>
                                                    <td class="si-pic"><img src="{{item.product.imageURL}}" alt=""></td>
                                                    <td class="si-text">
                                                        <div class="product-selected">
                                                            <p>Ksh{{item.product.price |intcomma}} x{{item.quantity}}</p>
                                                            <h6>{{item.product.name}}</h6>
                                                        </div>
                                                    </td>
                                                    <td class="si-close">
                                                        <i class="ti-close"></i>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="select-total">
                                        <span>total:</span>
                                        <h5>${{order.get_cart_total | intcomma}}</h5>
                                    </div>
                                    <div class="select-button">
                                        <a href="{% url 'cart' %}" class="primary-btn view-card">CART PAGE</a>
                                        <a href="{% url 'checkout' %}" class="primary-btn checkout-btn">CHECK OUT</a>
                                    </div>
                                </div>
                            </li>
                            <li class="cart-price">Ksh {{order.get_cart_total |intcomma}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="nav-item">
            <div class="container">
                <div class="nav-depart">
                    <div class="depart-btn">
                        <i class="ti-menu"></i>
                        <span>All categories</span>
                        <ul class="depart-hover">
                        {% for category in category %}
                            <li class=""><a href="{% url 'category' category.id %}">{{category.title}}</a></li>
                            
                        {% endfor %}
                        </ul>
                    </div>
                </div>
                <nav class="nav-menu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'store' %}">Shop</a></li>

                        
                        {% comment %} <li><a href="#">Collection</a>
                            <ul class="dropdown">
                            {% for category in Categories%}
                                <li><a href="#">{{category.title}}</a></li>
                            {% endfor %}
                            </ul>
                        </li> {% endcomment %}
                        <li class="active"><a href="{% url 'about' %}">About</a></li>
                        <li><a href="{% url 'newsletter'%}">Contact</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="dropdown">
                                <li><a href="{% url 'cart' %}">Shopping Cart</a></li>
                                <li><a href="{% url 'checkout' %}">Checkout</a></li>
                                <li><a href="{% url 'newsletter'%}">About us</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <div id="mobile-menu-wrap"></div>
            </div>
        </div>
    </header>
    <!-- Header End -->

    {% endblock header %}